<a href="https://colab.research.google.com/github/Divyaniwath02/Pattern_Recognition/blob/main/Practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install pandas numpy scikit-learn nltk openpyxl -q

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import (
    euclidean_distances,
    manhattan_distances,
    cosine_similarity
)
from nltk.metrics import edit_distance
import nltk

nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [6]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx"

df = pd.read_excel(url)

print("Dataset Loaded")
print(df.shape)


Dataset Loaded
(541909, 8)


In [7]:
df = df.dropna(subset=["CustomerID"])


In [8]:
customer = (
    df.groupby("CustomerID")
    .agg({
        "Quantity":"sum",
        "UnitPrice":"mean"
    })
    .reset_index()
)

customer.columns = [
    "CustomerID",
    "Total_Quantity",
    "Avg_Price"
]

print("\nCustomer Profiles")
print(customer.head())


Customer Profiles
   CustomerID  Total_Quantity  Avg_Price
0     12346.0               0   1.040000
1     12347.0            2458   2.644011
2     12348.0            2341   5.764839
3     12349.0             631   8.289041
4     12350.0             197   3.841176


In [9]:
features = customer[
    ["Total_Quantity","Avg_Price"]
]

scaler = StandardScaler()

scaled = scaler.fit_transform(features)

In [11]:
euclidean = euclidean_distances(scaled)

print("\nEuclidean Distance Matrix")
print(euclidean[:5,:5])


Euclidean Distance Matrix
[[0.         0.52620053 0.50210196 0.14401514 0.0463817 ]
 [0.52620053 0.         0.03302501 0.39296627 0.48399085]
 [0.50210196 0.03302501 0.         0.36640428 0.45907081]
 [0.14401514 0.39296627 0.36640428 0.         0.09782618]
 [0.0463817  0.48399085 0.45907081 0.09782618 0.        ]]


In [12]:
manhattan = manhattan_distances(scaled)

print("\nManhattan Distance Matrix")
print(manhattan[:5,:5])



Manhattan Distance Matrix
[[0.         0.53715036 0.53363979 0.18506428 0.06148934]
 [0.53715036 0.         0.04657229 0.42997718 0.49217972]
 [0.53363979 0.04657229 0.         0.38340489 0.47215045]
 [0.18506428 0.42997718 0.38340489 0.         0.12357494]
 [0.06148934 0.49217972 0.47215045 0.12357494 0.        ]]


In [13]:
cosine = cosine_similarity(scaled)

cosine_df = pd.DataFrame(
    cosine,
    index=customer["CustomerID"],
    columns=customer["CustomerID"]
)

print("\nCosine Similarity")
print(cosine_df.iloc[:5,:5])



Cosine Similarity
CustomerID   12346.0   12347.0   12348.0   12349.0   12350.0
CustomerID                                                  
12346.0     1.000000 -0.947733 -0.967615  0.976533  0.998566
12347.0    -0.947733  1.000000  0.997582 -0.994209 -0.963455
12348.0    -0.967615  0.997582  1.000000 -0.999273 -0.979741
12349.0     0.976533 -0.994209 -0.999273  1.000000  0.986663
12350.0     0.998566 -0.963455 -0.979741  0.986663  1.000000


In [14]:
country1 = str(df["Country"].iloc[0])
country2 = str(df["Country"].iloc[50])

ed = edit_distance(
    country1,
    country2
)

print("\nEdit Distance")
print(country1, "-", country2)
print("Distance:", ed)


Edit Distance
United Kingdom - United Kingdom
Distance: 0


In [17]:
cust = customer["CustomerID"].iloc[0]

similar = cosine_df.loc[cust]

# remove current customer
similar = similar.drop(cust)

# sort and select top 5
top5 = similar.sort_values(
    ascending=False
).head(5)

print("Selected Customer:", cust)

print("\nTop 5 Similar Customers:")
print(top5)

Selected Customer: 12346.0

Top 5 Similar Customers:
CustomerID
14467.0    1.0
13166.0    1.0
17520.0    1.0
14342.0    1.0
16239.0    1.0
Name: 12346.0, dtype: float64
